<?php

/*
Plugin Name:    Context Disable WordPress Version
Description:    Don't display WordPress generator/version publically.
Text-Domain:    cxt-disable-version
Version:        1.0
Author:         Robert Andrews
Author URI:     http://www.robertandrews.co.uk
License:        GPL v2 or later
License URI:    https://www.gnu.org/licenses/gpl-2.0.html
*/


/*
1.
Stops this header being generated by wp_head:
<meta name="generator" content="WordPress <?php bloginfo('version'); ?>" />
Also stops version being generated for RSS feeds.
cf. https://www.wpbeginner.com/wp-tutorials/the-right-way-to-remove-wordpress-version-number/
*/
function wpbeginner_remove_version() {
return '';
}
add_filter('the_generator', 'wpbeginner_remove_version');

/*
2.
Remove wp version number from scripts and styles.
By @sajid,
https://artisansweb.net/remove-version-css-js-wordpress/#:~:text=add_filter(%20'style_loader_src'%20%2C%20',all%20your%20styles%20and%20scripts.
*/
function remove_css_js_version( $src ) {
if( strpos( $src, '?ver=' ) )
$src = remove_query_arg( 'ver', $src );
return $src;
}
add_filter( 'style_loader_src', 'remove_css_js_version', 9999 );
add_filter( 'script_loader_src', 'remove_css_js_version', 9999);

?>